{% set version = "0.29.4" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rayrender
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rayrender_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rayrender/rayrender_{{ version }}.tar.gz
  sha256: 6202bd9bfbf19e32729db2d73fe53f5ea54b54e8c508b48153717e9d548886e3

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-rcppthread
    - r-decido
    - r-magrittr
    - r-png
    - r-progress
    - r-purrr
    - r-raster
    - r-rayimage >=0.9.0
    - r-spacefillr >=0.3.0
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-rcpp >=1.0.0
    - r-rcppthread
    - r-decido
    - r-magrittr
    - r-png
    - r-progress
    - r-purrr
    - r-raster
    - r-rayimage >=0.9.0
    - r-spacefillr >=0.3.0

test:
  commands:
    - $R -e "library('rayrender')"           # [not win]
    - "\"%R%\" -e \"library('rayrender')\""  # [win]

about:
  home: https://www.rayrender.net, https://github.com/tylermorganwall/rayrender
  license: GPL-3.0-only
  summary: Render scenes using pathtracing. Build 3D scenes out of spheres, cubes, planes, disks, triangles, cones, curves, line segments, cylinders, ellipsoids, and 3D models in the 'Wavefront' OBJ file format or the PLY Polygon File Format. Supports several material types, textures, multicore rendering, and tone-mapping.
    Based on the "Ray Tracing in One Weekend" book series. Peter Shirley (2018) <https://raytracing.github.io>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - ocefpaf
