{% set version = "0.34.3" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-rayrender
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/rayrender_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/rayrender/rayrender_{{ version }}.tar.gz
  sha256: afec5de304282ceeb57cfd0978d8e1392f565508fed36251dcbd327b499b99b5

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcpp >=1.0.0
    - r-rcppthread
    - r-assertthat
    - r-decido
    - r-magrittr
    - r-png
    - r-progress
    - r-purrr
    - r-raster
    - r-rayimage
    - r-rayvertex
    - r-spacefillr
    - r-tibble
    - r-withr
  run:
    - r-base
    - r-rcpp >=1.0.0
    - r-rcppthread
    - r-assertthat
    - r-decido
    - r-magrittr
    - r-png
    - r-progress
    - r-purrr
    - r-raster
    - r-rayimage
    - r-rayvertex
    - r-spacefillr
    - r-tibble
    - r-withr

test:
  commands:
    - $R -e "library('rayrender')"           # [not win]
    - "\"%R%\" -e \"library('rayrender')\""  # [win]

about:
  home: https://www.rayrender.net, https://github.com/tylermorganwall/rayrender

  license: GPL-3.0-or-later
  summary: Render scenes using pathtracing. Build 3D scenes out of spheres, cubes, planes, disks, triangles, cones, curves, line segments, cylinders, ellipsoids, and 3D models in the 'Wavefront' OBJ file format or the PLY Polygon File Format. Supports several material types, textures, multicore rendering, and tone-mapping.
    Based on the "Ray Tracing in One Weekend" book series. Peter Shirley (2018) <https://raytracing.github.io>.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - ocefpaf
    - conda-forge/r
